#!/usr/bin/env bash
# hero demo recorder — orchestrates the whole pipeline:
#
#   ┌──────────────────────────────────────────────────────────┐
#   │  Python pty.fork()                                       │
#   │    ├─ child : exec asciinema rec -c hero.runner.sh cast  │
#   │    │            └─ execs mnml --demo (in a real PTY)     │
#   │    │            └─ background driver feeds IPC commands  │
#   │    └─ parent: drains child pty (discards output)         │
#   │                sets winsize so mnml renders at hero dims │
#   └──────────────────────────────────────────────────────────┘
#
# Then agg converts the .cast to a GIF and we mirror it to
# site/public/media/hero.gif + assets/demo.gif.
#
# Why this exists rather than VHS:
#   VHS 0.11.0 on macOS 26.5.1 renders one keystroke and stops
#   (chromium-in-ttyd frame capture regression). asciinema + agg
#   is the standard TUI-recording stack and works reliably.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
TAPE_DIR="$REPO/demo/tapes"

# 2026-08-15 — first positional arg picks which driver to run.
# `hero` (default) drives the full walkthrough; per-integration
# tapes (`jira`, `bitbucket`, `slack`, etc.) drive a shorter
# focused walkthrough of one section. Each driver lives at
# `demo/tapes/<name>.driver.sh` and outputs to
# `site/public/media/<name>.gif`.
TAPE_NAME="${1:-hero}"
DRIVER="$TAPE_DIR/${TAPE_NAME}.driver.sh"
if [ ! -x "$DRIVER" ]; then
  echo "[demo-record] driver not found: $DRIVER" >&2
  echo "  available: $(ls "$TAPE_DIR"/*.driver.sh 2>/dev/null | xargs -n1 basename | sed 's/\.driver\.sh$//' | tr '\n' ' ')" >&2
  exit 1
fi

# Recording dimensions. Wider than a normal terminal to show all
# activity-bar tooltips + right-panel + statusline chips at once.
# 2026-08-15 — was 180x46, GIF landed at ~2548x921 (2.76:1) which
# reads as awkwardly wide on both the mnml.sh hero + README. 140x36
# lands ~1960x820 ≈ 2.4:1 (still wide but not letterbox-flat) and
# keeps enough room for the split-pane climax to be legible.
COLS="${MNML_DEMO_COLS:-140}"
ROWS="${MNML_DEMO_ROWS:-36}"

# Font size for agg. 14px keeps a 1600x900 GIF sane in file size
# while staying legible for a hero splash.
FONT_SIZE="${MNML_DEMO_FONT_SIZE:-14}"

CAST="$TAPE_DIR/${TAPE_NAME}.cast"
GIF_OUT="$REPO/site/public/media/${TAPE_NAME}.gif"
# Only the hero mirrors to assets/demo.gif for the README embed.
# Per-integration tapes stay under site/public/media/.
if [ "$TAPE_NAME" = "hero" ]; then
  GIF_MIRROR="$REPO/assets/demo.gif"
else
  GIF_MIRROR=""
fi

# ── Preflight ─────────────────────────────────────────────────
need() { command -v "$1" >/dev/null 2>&1 || { echo "[demo-record] missing: $1"; exit 1; }; }
need asciinema
need agg
need python3

if [ ! -x "$REPO/target/release/mnml" ]; then
  echo "[demo-record] building release binary…"
  (cd "$REPO" && cargo build --release --quiet)
fi

# Kill any stale demo-mnml (from a prior run) so we own the IPC dir
pkill -f "target/release/mnml --demo" 2>/dev/null || true
# Reset the IPC state so the driver's wait-for-boot is deterministic.
rm -f "$REPO/demo/workspace/.mnml/ipc/command" \
      "$REPO/demo/workspace/.mnml/ipc/events.jsonl" \
      "$REPO/demo/workspace/.mnml/ipc/screen.txt" \
      "$REPO/demo/workspace/.mnml/ipc/status.json"
mkdir -p "$REPO/demo/workspace/.mnml/ipc"
: > "$REPO/demo/workspace/.mnml/ipc/command"

# Wipe the persisted session so mnml boots to its welcome view
# instead of restoring whatever tabs were open on the last dev
# launch. The driver's `open` command re-opens what we need.
rm -f "$REPO/demo/workspace/.mnml/session.json"

# ── Demo HOME for sibling integrations ────────────────────────
# The Jira / Bitbucket / GitHub siblings hardcode their config
# + token paths to `$HOME/.config/mnml-*/…` — no env-var override.
# So the per-integration override .toml files (which inject
# JIRA_SITE_URL etc.) don't reach the sibling: it reads its own
# TOML from HOME and ignores whatever env we set.
#
# Fix: build a throwaway HOME dir seeded with demo configs
# pointing at the mock server, and invoke each sibling via
# `env HOME=$DEMO_HOME <sibling> --only <family>` from the driver.
# See demo/tapes/{jira,bitbucket}.driver.sh which invoke the
# sibling wrapped in `env HOME=$MNML_DEMO_SIBLING_HOME …`.
DEMO_SIBLING_HOME="$REPO/demo/tapes/.sibling-home"
rm -rf "$DEMO_SIBLING_HOME"
mkdir -p "$DEMO_SIBLING_HOME/.config/mnml-tracker-jira" \
         "$DEMO_SIBLING_HOME/.config/mnml-forge-bitbucket"

# Jira demo config → mock server.
cat > "$DEMO_SIBLING_HOME/.config/mnml-tracker-jira.toml" <<'TOML'
# Demo config for the recording pipeline — points at the mock
# server at localhost:7071. Auto-regenerated by hero.record.sh.
jira_url = "http://localhost:7071/jira"
email    = "ava@bloomlabs.dev"
refresh_interval_secs = 0
[[tabs]]
name = "Active Sprint"
kind = "board_active_sprint"
project = "NTL"
board_id = 42
[[tabs]]
name = "Backlog"
kind = "board_backlog"
project = "NTL"
board_id = 42
TOML
printf 'demo-token-notely' > "$DEMO_SIBLING_HOME/.config/mnml-tracker-jira/token"
chmod 600 "$DEMO_SIBLING_HOME/.config/mnml-tracker-jira/token"

# Bitbucket demo config → mock server.
cat > "$DEMO_SIBLING_HOME/.config/mnml-forge-bitbucket.toml" <<'TOML'
# Demo config for the recording pipeline — points at the mock
# server at localhost:7071. Auto-regenerated by hero.record.sh.
base_url  = "http://localhost:7071/bitbucket"
email     = "ava@bloomlabs.dev"
workspace = "bloomlabs"
refresh_interval_secs = 0
scope     = "all"
[[tabs]]
name = "Open + Draft"
kind = "workspace_open_prs"
[[tabs]]
name = "Merged"
kind = "workspace_merged_prs"
TOML
printf 'demo-token-notely' > "$DEMO_SIBLING_HOME/.config/mnml-forge-bitbucket/token"
chmod 600 "$DEMO_SIBLING_HOME/.config/mnml-forge-bitbucket/token"

export MNML_DEMO_SIBLING_HOME="$DEMO_SIBLING_HOME"

mkdir -p "$(dirname "$GIF_OUT")"
[ -n "$GIF_MIRROR" ] && mkdir -p "$(dirname "$GIF_MIRROR")"

# ── The inner shell command asciinema runs ───────────────────
# We use a heredoc so no third script file needs to exist. The
# driver runs in the background; mnml runs in the foreground so
# asciinema follows its stdout.
INNER_SCRIPT="$(mktemp -t mnml-hero-inner.XXXXXX.sh)"
trap 'rm -f "$INNER_SCRIPT"' EXIT
cat > "$INNER_SCRIPT" <<INNER
#!/usr/bin/env bash
set -euo pipefail
export MNML_DEMO_WORKSPACE="$REPO/demo/workspace"
export MNML_DEMO_SIBLING_HOME="$DEMO_SIBLING_HOME"

# Demo integration env vars — inherited by any Pty pane mnml
# spawns (via :term / open-pty IPC), so the jira / bitbucket
# / github siblings hit the mock server on localhost:7071
# instead of real Atlassian / real Bitbucket.
#
# Redundant with the per-workspace <id>.override.toml files —
# those inject the same vars via the integration-manifest
# layer, but only for integrations whose manifest id matches
# the override filename. In the current repo the override
# files use legacy ids (jira / bitbucket / github) that don't
# match the current sibling ids (jira_boards / bitbucket_prs).
# Exporting here at the process level is the belt-and-braces
# fallback until the override files get renamed to match.
# (Filed: see the report from the demo-expansion pass.)
export JIRA_SITE_URL="http://localhost:7071/jira"
export JIRA_BASE_URL="http://localhost:7071/jira"
export JIRA_EMAIL="ava@bloomlabs.dev"
export JIRA_API_TOKEN="demo-token-notely"
export JIRA_PROJECT="NTL"
export BITBUCKET_BASE_URL="http://localhost:7071/bitbucket"
export BITBUCKET_USER="avachen"
export BITBUCKET_ACCESS_TOKEN="demo-token-notely"
export BITBUCKET_APP_PASSWORD="demo-token-notely"
export BITBUCKET_WORKSPACE="bloomlabs"
export BITBUCKET_REPO="notely"
export GITHUB_BASE_URL="http://localhost:7071/github"
export GITHUB_TOKEN="demo-token-notely"
export GITHUB_OWNER="bloomlabs"
export GITHUB_REPO="notely"

# Start the driver in the background — it polls for mnml's IPC
# dir, then feeds JSONL commands with pacing.
"$DRIVER" &
DRIVER_PID=\$!
trap "kill \$DRIVER_PID 2>/dev/null || true" EXIT
# Exec mnml in the foreground so asciinema captures its output.
# The driver's final command is {"cmd":"quit"} — mnml exits, this
# process exits, asciinema finalizes the cast.
exec "$REPO/target/release/mnml" --demo
INNER
chmod +x "$INNER_SCRIPT"

# ── Record ────────────────────────────────────────────────────
rm -f "$CAST"
echo "[demo-record] recording ${COLS}x${ROWS} → $CAST"
python3 - <<PY
import os, sys, pty, struct, fcntl, termios, select

argv = ["asciinema", "rec",
        "-c", "$INNER_SCRIPT",
        "$CAST",
        "--overwrite",
        "--quiet"]

pid, fd = pty.fork()
if pid == 0:
    os.execvp(argv[0], argv)

# Parent — set the pty winsize so mnml paints at demo dims,
# then drain the child stdout (discard; asciinema writes the
# cast file itself).
size = struct.pack("HHHH", int($ROWS), int($COLS), 0, 0)
fcntl.ioctl(fd, termios.TIOCSWINSZ, size)

while True:
    try:
        r, _, _ = select.select([fd], [], [], 0.5)
        if fd in r:
            data = os.read(fd, 4096)
            if not data:
                break
    except OSError:
        break

_, status = os.waitpid(pid, 0)
sys.exit(0 if os.WIFEXITED(status) else 1)
PY

if [ ! -s "$CAST" ]; then
  echo "[demo-record] cast is empty — mnml never rendered"
  exit 1
fi

echo "[demo-record] cast size (raw): $(du -h "$CAST" | cut -f1)"

# ── Trim head + tail ─────────────────────────────────────────
# Two edits, both improve the final GIF:
#   * Head: drop the ~2s black-cursor dwell before mnml's first
#     paint. asciinema time-stamps the alt-screen setup at
#     ~0.3s but mnml's first real paint doesn't land for another
#     ~2s (release-build boot + backend init). Without trimming,
#     the GIF opens on a blank canvas.
#   * Tail: mnml's clean-shutdown sequence sends `\x1b[?1049l`
#     (leave alt screen) which wipes the terminal to blank in
#     the recording. Because the final frame drives the static
#     preview AND what viewers see between loop iterations, we
#     strip from the leave-alt-screen event onward and append a
#     long dwell on the last mnml-rendered frame.
python3 - <<PY
import json, sys
CAST = "$CAST"
with open(CAST) as f:
    header = f.readline()
    events = [line.rstrip("\n") for line in f if line.strip()]

def payload_of(line):
    try:
        ev = json.loads(line)
    except json.JSONDecodeError:
        return ""
    return ev[2] if len(ev) >= 3 and isinstance(ev[2], str) else ""

# HEAD — find the first event that actually paints characters
# (not just a mode-set escape) and squash the delay-to-first-
# paint down to a small dwell so the GIF opens on real content.
FIRST_PAINT_MIN_LEN = 200  # characters — real mnml frames are large
head_cut = 0
for i, line in enumerate(events):
    p = payload_of(line)
    if len(p) >= FIRST_PAINT_MIN_LEN:
        head_cut = i
        break
if head_cut > 0:
    # Compress the delay on the first paint to 0.5s (short but
    # long enough that viewers register the transition).
    ev = json.loads(events[head_cut])
    ev[0] = 0.5
    events[head_cut] = json.dumps(ev)
    events = events[head_cut:]

# TAIL — cut at leave-alt-screen.
tail_cut = None
for i, line in enumerate(events):
    if "\x1b[?1049l" in payload_of(line):
        tail_cut = i
        break
if tail_cut is not None:
    events = events[:tail_cut]

# Long dwell on the last mnml frame.
events.append(json.dumps([2.5, "o", ""]))

with open(CAST, "w") as f:
    f.write(header)
    for e in events:
        f.write(e + "\n")
print(f"[demo-record] trimmed cast: {len(events)} events")
PY

echo "[demo-record] cast size (trimmed): $(du -h "$CAST" | cut -f1)"

# ── Convert cast → GIF via agg ────────────────────────────────
# --idle-time-limit clamps long pauses (the driver's sleep_ms
# waits) so the GIF loops in a reasonable time.
# --font-family prefers Nerd-Font-embedded monospace so the
# activity-bar icons + statusline glyphs render (falls back on
# platform monospaces if Nerd Font isn't installed).
echo "[demo-record] rendering GIF → $GIF_OUT"
agg --cols "$COLS" --rows "$ROWS" \
    --font-size "$FONT_SIZE" \
    --font-family "JetBrainsMono Nerd Font Mono,JetBrains Mono" \
    --theme monokai \
    --idle-time-limit 2 \
    --fps-cap 20 \
    "$CAST" "$GIF_OUT"

# Mirror to the GitHub README asset location (hero only).
if [ -n "$GIF_MIRROR" ]; then
  cp "$GIF_OUT" "$GIF_MIRROR"
fi

# ── Extract review frames ─────────────────────────────────────
# Pull 8 evenly-spaced frames out of the rendered GIF so a
# downstream reviewer (human OR an agent invoked with a `frames/`
# manifest) can pattern-match "frame N should show X" against the
# driver script's inline beat comments.
#
# Total frame count varies with the .cast's --fps-cap output;
# ffmpeg's `select='not(mod(n,K))'` needs a step K to yield ~8.
# We probe the frame count with ffprobe (fast — the GIF is small)
# and compute K = max(1, round(total / 8)).
FRAMES_DIR="$REPO/demo/tapes/frames/$TAPE_NAME"
if command -v ffmpeg >/dev/null 2>&1; then
  rm -rf "$FRAMES_DIR"
  mkdir -p "$FRAMES_DIR"
  # Sample by WALL-CLOCK TIME, not by frame index. Frame-index
  # sampling clusters on high-activity moments (many short-duration
  # frames) and skips the calm dwell segments an animated tape
  # actually cares about (the ~2s hero-shot hold, the ticker
  # rotations). Time-based sampling gives 8 evenly-spaced snapshots
  # across the GIF's real duration, which is what a downstream
  # reviewer needs to pattern-match "at t=NN%, screen should show X".
  duration="$(ffprobe -v error -select_streams v:0 \
                -show_entries stream=duration -of csv=p=0 \
                "$GIF_OUT" 2>/dev/null || echo '')"
  # Fallback to format-level duration if the stream one is missing.
  if ! [[ "$duration" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
    duration="$(ffprobe -v error -show_entries format=duration \
                  -of csv=p=0 "$GIF_OUT" 2>/dev/null || echo '')"
  fi
  if [[ "$duration" =~ ^[0-9]+(\.[0-9]+)?$ ]] \
     && awk "BEGIN{exit !($duration > 0.5)}"; then
    # Emit 8 frames at t = 5%, 15%, 30%, 45%, 60%, 75%, 88%, 97%
    # of duration. The uneven spacing skews slightly toward the
    # middle-and-end (where the composite hero shots typically
    # land) so the review sample reflects "what viewers actually
    # remember" from the tape.
    pcts=(0.05 0.15 0.30 0.45 0.60 0.75 0.88 0.97)
    i=1
    for p in "${pcts[@]}"; do
      t="$(awk "BEGIN{printf \"%.3f\", $duration * $p}")"
      # -ss BEFORE -i does input-side seek (fast); -frames:v 1
      # emits one PNG. Suppress ffmpeg banner + stderr progress.
      ffmpeg -y -loglevel error \
        -ss "$t" -i "$GIF_OUT" \
        -frames:v 1 \
        "$(printf '%s/frame_%03d.png' "$FRAMES_DIR" "$i")"
      i=$(( i + 1 ))
    done
    n_frames="$(ls "$FRAMES_DIR"/frame_*.png 2>/dev/null | wc -l | tr -d ' ')"
    echo "  frames        $FRAMES_DIR ($n_frames PNGs @ 5/15/30/45/60/75/88/97% of ${duration}s)"
  else
    echo "[demo-record] could not read GIF duration — skipping frame extraction"
  fi
else
  echo "[demo-record] ffmpeg not on PATH — skipping frame extraction"
  echo "              (install with: brew install ffmpeg)"
fi

echo "[demo-record] done"
echo "  cast          $CAST ($(du -h "$CAST" | cut -f1))"
echo "  site GIF      $GIF_OUT ($(du -h "$GIF_OUT" | cut -f1))"
if [ -n "$GIF_MIRROR" ]; then
  echo "  README mirror $GIF_MIRROR ($(du -h "$GIF_MIRROR" | cut -f1))"
fi
