//! `mnml-libghostty-vt-sys` — raw FFI bindings to Ghostty's [libghostty-vt] C ABI.
//!
//! The upstream C headers are vendored under `vendor/libghostty-vt/` at the
//! workspace root; bindings are generated by `bindgen` at build time (see
//! `build.rs`). Linking goes through `zig build` — build.rs clones ghostty
//! at the pinned `GHOSTTY_COMMIT`, runs zig, and links the produced `.a`.
//! Needs zig 0.16.0 + git on PATH.
//!
//! This crate exposes the C API essentially verbatim. Ergonomic wrappers
//! (safe iterators, typed handles, RAII destruction) live in the
//! [`mnml-libghostty-vt`] sibling crate — mnml core depends on that one, not this.
//!
//! [libghostty-vt]: https://github.com/ghostty-org/ghostty/tree/main/include/ghostty

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
