//! Enumerate the vendored `themes/*.lua` (NvChad base46) colour schemes and emit
//! a `THEME_SOURCES: &[(&str, &str)]` table (name → file contents, via
//! `include_str!`) for `src/ui/theme.rs` to parse at startup.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("themes");
    println!("cargo:rerun-if-changed=themes");

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().and_then(|x| x.to_str()) == Some("lua")
                && let Some(stem) = p.file_stem().and_then(|s| s.to_str())
            {
                entries.push((stem.to_string(), p.to_string_lossy().into_owned()));
            }
        }
    }
    entries.sort();

    let mut out = String::from(
        "// @generated by build.rs — the vendored base46 themes (name, file contents).\n\
         pub const THEME_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &entries {
        out.push_str(&format!("    ({name:?}, include_str!({path:?})),\n"));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("theme_sources.rs");
    fs::write(dest, out).expect("write theme_sources.rs");
}
