//! The commands reference page: one table per namespace (the palette
//! group), one row per id with the title and the default chords of
//! each keymap profile. `zig build docs` writes it to `docs/commands.md`
//! (`tools/gen_commands.zig`); `view.commands_reference` opens the same
//! text as a scratch buffer. The rows come from the comptime `specs`
//! the binary is built from, so neither can drift from the ids the way
//! a hand-kept list did (E8: 695 documented vs 797 real).

const std = @import("std");
const specs_mod = @import("specs.zig");
pub const specs = specs_mod.specs;
pub const Spec = specs_mod.Spec;

/// The namespaces, in first-appearance order.
pub const groups: []const []const u8 = blk: {
    @setEvalBranchQuota(200_000);
    var out: []const []const u8 = &.{};
    for (specs) |s| {
        var seen = false;
        for (out) |g| if (std.mem.eql(u8, g, s.group)) {
            seen = true;
        };
        if (!seen) out = out ++ &[_][]const u8{s.group};
    }
    break :blk out;
};

pub fn render(arena: std.mem.Allocator, w: *std.Io.Writer) !void {
    try w.writeAll("# Commands\n\n");
    try w.print("Generated by `zig build docs` from `src/commands/specs.zig` — do not edit by hand. {d} commands in {d} groups. A chord is the default for that keymap profile (`editor.input_style`); an empty cell means the command is reachable from the palette (`ctrl+shift+p`) and the `:` line only.\n\n", .{ specs.len, groups.len });
    try w.writeAll("| group | commands |\n|---|---|\n");
    for (groups) |g| try w.print("| [`{s}`](#{s}) | {d} |\n", .{ g, g, countIn(g) });
    try w.writeAll("\n");
    for (groups) |g| {
        try w.print("## {s}\n\n| id | title | vim | standard |\n|---|---|---|---|\n", .{g});
        const rows = try sortedIn(arena, g);
        for (rows) |s| {
            try w.print("| `{s}` | {s} | {s} | {s} |\n", .{
                s.id,
                try escape(arena, s.title),
                try chords(arena, s.keys.vim, s.keys.both, s.keys.vim_handler),
                try chords(arena, s.keys.standard, s.keys.both, &.{}),
            });
        }
        try w.writeAll("\n");
    }
}

fn countIn(group: []const u8) usize {
    var n: usize = 0;
    for (specs) |s| n += @intFromBool(std.mem.eql(u8, s.group, group));
    return n;
}

fn sortedIn(arena: std.mem.Allocator, group: []const u8) ![]const Spec {
    var rows: std.ArrayListUnmanaged(Spec) = .empty;
    for (specs) |s| if (std.mem.eql(u8, s.group, group)) try rows.append(arena, s);
    std.mem.sort(Spec, rows.items, {}, struct {
        fn lt(_: void, a: Spec, b: Spec) bool {
            return std.mem.lessThan(u8, a.id, b.id);
        }
    }.lt);
    return rows.items;
}

/// The profile's own chords, then the shared ones, then the ones the vim
/// handler answers itself (`Ctrl-W w`), as `` `a`, `b` ``.
fn chords(arena: std.mem.Allocator, own: []const []const u8, both: []const []const u8, handler: []const []const u8) ![]const u8 {
    var out: std.Io.Writer.Allocating = .init(arena);
    var first = true;
    for ([_][]const []const u8{ own, both, handler }) |list| for (list) |k| {
        if (!first) try out.writer.writeAll(", ");
        first = false;
        try out.writer.print("`{s}`", .{k});
    };
    return out.written();
}

/// A title with `|` escaped so it stays one cell.
fn escape(arena: std.mem.Allocator, s: []const u8) ![]const u8 {
    if (std.mem.indexOfScalar(u8, s, '|') == null) return s;
    return std.mem.replaceOwned(u8, arena, s, "|", "\\|");
}

// ─── tests ──────────────────────────────────────────────────────────────

const t = std.testing;

test "the page names every id, every group once, and each profile's chords" {
    var arena_state = std.heap.ArenaAllocator.init(t.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    var out: std.Io.Writer.Allocating = .init(arena);
    try render(arena, &out.writer);
    const page = out.written();
    for (specs) |s| {
        const cell = try std.fmt.allocPrint(arena, "| `{s}` |", .{s.id});
        try t.expect(std.mem.indexOf(u8, page, cell) != null);
    }
    for (groups) |g| {
        const heading = try std.fmt.allocPrint(arena, "\n## {s}\n", .{g});
        try t.expectEqual(@as(usize, 1), std.mem.count(u8, page, heading));
    }
    // app.quit is `ctrl+q` on both profiles: the chord lands in both cells.
    try t.expect(std.mem.indexOf(u8, page, "| `app.quit` | Quit mnml | `ctrl+q` | `ctrl+q` |") != null);
    try t.expect(std.mem.indexOf(u8, page, "# Commands") != null);
}
