//! Hover help for the file tree: the workspace roots, the header chips,
//! the empty rows, and every row — a directory, a known filename, a
//! known extension (the Rust dictionary's tree and filename sections,
//! `filename_row_copy` / `tree_row_copy`), else the generic line.

const std = @import("std");
const Allocator = std.mem.Allocator;
const app_mod = @import("../../app.zig");
const App = app_mod.App;
const copy = @import("../info_view_copy.zig");
const Entry = copy.Entry;
const Key = copy.Key;
const tree_view = @import("../../ui/tree_view.zig");
const tree_mod = @import("../tree.zig");
const icons = @import("../../ui/icons.zig");

const ask = copy.ask_link;

const open_keys = [_]Key{
    .{ .chord = "Enter", .label = "Open in the active pane" },
};

const dir_keys = [_]Key{
    .{ .chord = "Enter", .label = "Expand / collapse" },
    .{ .chord = "→ / ←", .label = "Expand / collapse (arrows)" },
};

const Row = struct { key: []const u8, lang: []const u8, body: []const u8 };

/// Whole-filename rows (Rust `filename_row_copy`), lower-cased.
const by_name = [_]Row{
    .{ .key = "package.json", .lang = "npm manifest", .body = "Declares this package's dependencies, scripts, and metadata for npm / pnpm / yarn. Syntax-only highlighting; no schema validation. `npm run <script>` from a terminal pane runs anything listed under `scripts`." },
    .{ .key = "dockerfile", .lang = "Dockerfile", .body = "Defines how `docker build` assembles an image — base layer, copied files, entrypoint. Syntax-only highlighting. `:!docker build .` from the cmdline works if docker is on PATH." },
    .{ .key = ".env", .lang = "Environment variables", .body = "Untracked key=value pairs the process reads at startup. This is separate from mnml's own `{{VAR}}` substitution, which reads `.mnml/env/<name>.env` in Request panes. Treat this file as secrets — keep it out of git." },
    .{ .key = "makefile", .lang = "Build recipes", .body = "Defines named targets (`make build`, `make test`, …) as shell recipes. Tab-indentation is significant — a space where a tab is expected is the #1 Makefile syntax error. No LSP; syntax-only highlighting." },
    .{ .key = "package-lock.json", .lang = "npm lockfile", .body = "Exact dependency-tree snapshot npm resolved from `package.json`. Generated by `npm install` — don't hand-edit; a mismatch with `package.json` triggers a warning on the next install." },
    .{ .key = "pnpm-lock.yaml", .lang = "pnpm lockfile", .body = "Exact dependency-tree snapshot pnpm resolved from `package.json`. Generated by `pnpm install` — don't hand-edit." },
    .{ .key = "tsconfig.json", .lang = "TypeScript project config", .body = "Compiler options, path aliases, and `include`/`exclude` globs that tsserver reads to resolve module paths. A wrong `baseUrl` or `paths` entry here is the usual cause of false 'cannot find module' errors in the editor." },
    .{ .key = ".gitignore", .lang = "Git ignore rules", .body = "Path patterns excluded from `git status` / `git add`. mnml's own file picker excludes `.git/` unconditionally regardless of what's listed here." },
    .{ .key = ".gitattributes", .lang = "Git attributes", .body = "Per-path git behavior — line-ending normalization, diff drivers, merge strategies, archive export-ignore. Affects what `git` does with the file, not how mnml renders it." },
    .{ .key = ".gitconfig", .lang = "Git config", .body = "INI-style git settings — user identity, aliases, remotes. A repo's `.git/config` takes precedence over this one when both set the same key." },
    .{ .key = ".eslintrc", .lang = "ESLint config", .body = "Lint rules and plugin config for ESLint. mnml doesn't run ESLint itself — pair with a terminal pane (`eslint .`) or an LSP that surfaces its diagnostics." },
    .{ .key = ".prettierrc", .lang = "Prettier config", .body = "Formatting rules — quote style, semicolons, line width — for Prettier. mnml doesn't format on save from this file; run `prettier --write` from a terminal pane." },
    .{ .key = ".editorconfig", .lang = "EditorConfig", .body = "Cross-editor whitespace rules (indent size, tabs vs spaces, trailing newline) keyed by glob. mnml reads it for the indentation of the files it covers." },
    .{ .key = ".dockerignore", .lang = "Docker ignore rules", .body = "Paths excluded from the build context `docker build` sends to the daemon — same glob syntax as `.gitignore`. Keeping it tight speeds up builds and keeps secrets out of the image." },
    .{ .key = ".npmrc", .lang = "npm config", .body = "Per-project npm settings — registry URL, auth tokens, save-exact behavior. Treat auth-token lines as secrets and keep them out of git." },
    .{ .key = ".nvmrc", .lang = "Node version pin", .body = "A single line naming the Node version this project expects. `nvm use` (or an nvm-aware shell hook) reads it automatically on `cd`." },
    .{ .key = "docker-compose.yml", .lang = "Compose file", .body = "Defines the multi-container stack — services, networks, volumes — for `docker compose up`. Indentation-sensitive YAML, same as any other `.yml`; syntax-only highlighting." },
    .{ .key = "docker-compose.yaml", .lang = "Compose file", .body = "Defines the multi-container stack — services, networks, volumes — for `docker compose up`. Indentation-sensitive YAML, same as any other `.yml`; syntax-only highlighting." },
    .{ .key = "compose.yml", .lang = "Compose file", .body = "Defines the multi-container stack — services, networks, volumes — for `docker compose up`. Indentation-sensitive YAML, same as any other `.yml`; syntax-only highlighting." },
    .{ .key = "compose.yaml", .lang = "Compose file", .body = "Defines the multi-container stack — services, networks, volumes — for `docker compose up`. Indentation-sensitive YAML, same as any other `.yml`; syntax-only highlighting." },
    .{ .key = "readme", .lang = "Project readme", .body = "The first thing a visitor to this repo or folder reads. mnml renders it like any other Markdown file when `ui.render_markdown` is on; `:e` opens the raw source." },
    .{ .key = "readme.md", .lang = "Project readme", .body = "The first thing a visitor to this repo or folder reads. mnml renders it like any other Markdown file when `ui.render_markdown` is on; `:e` opens the raw source." },
    .{ .key = "license", .lang = "License text", .body = "The legal terms this project is distributed under. Plain text or Markdown depending on the project; mnml applies syntax-only highlighting either way." },
    .{ .key = "copying", .lang = "License text (GNU convention)", .body = "Same role as LICENSE — the GNU-project convention for the license filename, common on GPL-licensed code. Plain text; no highlighting." },
};

/// Extension rows (Rust `tree_row_copy`), lower-cased.
const by_ext = [_]Row{
    .{ .key = "rs", .lang = "Rust source", .body = "Compiled with cargo. Hover a symbol in the buffer for LSP info (once the LSP has warmed up)." },
    .{ .key = "ts", .lang = "TypeScript source", .body = "TypeScript / TSX. LSP fires once tsserver is up — takes a few seconds on first open of the workspace." },
    .{ .key = "tsx", .lang = "TypeScript source", .body = "TypeScript / TSX. LSP fires once tsserver is up — takes a few seconds on first open of the workspace." },
    .{ .key = "py", .lang = "Python source", .body = "Python. LSP via pyright once mnml detects a Python interpreter." },
    .{ .key = "md", .lang = "Markdown", .body = "Rendered inline by default when `ui.render_markdown` is on. `:e path.md` opens the raw editor instead." },
    .{ .key = "mdx", .lang = "Markdown", .body = "Rendered inline by default when `ui.render_markdown` is on. `:e path.md` opens the raw editor instead." },
    .{ .key = "toml", .lang = "TOML config", .body = "TOML config file. No LSP; syntax-only highlighting." },
    .{ .key = "json", .lang = "JSON data", .body = "JSON file. Syntax-only highlighting; use a `.http` or `.curl` file to send this as a request body." },
    .{ .key = "go", .lang = "Go source", .body = "Go. LSP fires once gopls is on PATH; module boundary comes from the nearest `go.mod`." },
    .{ .key = "sh", .lang = "Shell script", .body = "POSIX / bash / zsh script. No LSP by default; `:!chmod +x` on a new script makes it executable." },
    .{ .key = "bash", .lang = "Shell script", .body = "POSIX / bash / zsh script. No LSP by default; `:!chmod +x` on a new script makes it executable." },
    .{ .key = "zsh", .lang = "Shell script", .body = "POSIX / bash / zsh script. No LSP by default; `:!chmod +x` on a new script makes it executable." },
    .{ .key = "yaml", .lang = "YAML config", .body = "YAML config file. Indentation-sensitive — mnml paints trailing whitespace red when `ui.highlight_trailing_ws` is on." },
    .{ .key = "yml", .lang = "YAML config", .body = "YAML config file. Indentation-sensitive — mnml paints trailing whitespace red when `ui.highlight_trailing_ws` is on." },
    .{ .key = "js", .lang = "JavaScript", .body = "JavaScript / JSX. tsserver handles both TS and JS when it warms up, so LSP hover works even without types." },
    .{ .key = "jsx", .lang = "JavaScript", .body = "JavaScript / JSX. tsserver handles both TS and JS when it warms up, so LSP hover works even without types." },
    .{ .key = "html", .lang = "HTML markup", .body = "HTML. No LSP; syntax-only highlighting. Pair with a `.http` file next to it if this is a request-body template." },
    .{ .key = "htm", .lang = "HTML markup", .body = "HTML. No LSP; syntax-only highlighting. Pair with a `.http` file next to it if this is a request-body template." },
    .{ .key = "css", .lang = "Stylesheet", .body = "CSS / SCSS / SASS. Syntax-only highlighting; no LSP." },
    .{ .key = "scss", .lang = "Stylesheet", .body = "CSS / SCSS / SASS. Syntax-only highlighting; no LSP." },
    .{ .key = "sass", .lang = "Stylesheet", .body = "CSS / SCSS / SASS. Syntax-only highlighting; no LSP." },
    .{ .key = "sql", .lang = "SQL", .body = "SQL script. Syntax-only highlighting; no linter. Run against a live connection through your usual client — mnml doesn't execute." },
    .{ .key = "vue", .lang = "Vue single-file component", .body = "Vue 3 SFC — `<template>` / `<script>` / `<style>` blocks in one file. Syntax-only highlighting; no dedicated LSP yet." },
    .{ .key = "svelte", .lang = "Svelte component", .body = "Svelte single-file component — markup, script, and scoped styles together. Syntax-only highlighting; no LSP." },
    .{ .key = "c", .lang = "C source", .body = "C source file. Syntax-only highlighting; no LSP wired in yet." },
    .{ .key = "cpp", .lang = "C++ source", .body = "C++ source file. Syntax-only highlighting; no LSP wired in yet." },
    .{ .key = "h", .lang = "C/C++ header", .body = "Declarations only, no implementation. Syntax-only highlighting; no LSP." },
    .{ .key = "hpp", .lang = "C/C++ header", .body = "Declarations only, no implementation. Syntax-only highlighting; no LSP." },
    .{ .key = "java", .lang = "Java source", .body = "Java source file. Syntax-only highlighting; no LSP (jdtls isn't wired in yet)." },
    .{ .key = "kt", .lang = "Kotlin source", .body = "Kotlin source file. Syntax-only highlighting; no LSP." },
    .{ .key = "swift", .lang = "Swift source", .body = "Swift source file. Syntax-only highlighting; no LSP." },
    .{ .key = "cs", .lang = "C# source", .body = "C# source file. Syntax-only highlighting; no LSP wired in yet." },
    .{ .key = "csproj", .lang = "MSBuild project file", .body = "References, target framework, and package refs for a .NET project. XML under the hood; syntax-only highlighting." },
    .{ .key = "sln", .lang = "Visual Studio solution", .body = "Groups one or more `.csproj` projects for Visual Studio or `dotnet build`. Plain-text format; syntax-only highlighting." },
    .{ .key = "cshtml", .lang = "Razor page", .body = "ASP.NET Razor page — HTML markup with embedded C# `@` blocks. Syntax-only highlighting." },
    .{ .key = "razor", .lang = "Razor component", .body = "Blazor Razor component — HTML markup with embedded C#. Syntax-only highlighting." },
    .{ .key = "fs", .lang = "F# source", .body = "F# source file. Syntax-only highlighting; no LSP." },
    .{ .key = "xml", .lang = "XML data", .body = "XML markup. Syntax-only highlighting; no schema validation." },
    .{ .key = "svg", .lang = "SVG image", .body = "Scalable vector graphic — technically XML, but mnml treats it as an image. No inline preview; open it in a browser to see it rendered." },
    .{ .key = "png", .lang = "Image", .body = "Raster image. mnml shows it in an image pane when the terminal can draw one." },
    .{ .key = "jpg", .lang = "Image", .body = "Raster image. mnml shows it in an image pane when the terminal can draw one." },
    .{ .key = "jpeg", .lang = "Image", .body = "Raster image. mnml shows it in an image pane when the terminal can draw one." },
    .{ .key = "gif", .lang = "Image", .body = "Raster image. mnml shows it in an image pane when the terminal can draw one." },
    .{ .key = "webp", .lang = "Image", .body = "Raster image. mnml shows it in an image pane when the terminal can draw one." },
    .{ .key = "http", .lang = "HTTP request file", .body = "mnml's own request format — method, URL, headers, and body in one file. Opening it launches the Request pane UI instead of a plain-text editor." },
    .{ .key = "curl", .lang = "HTTP request file", .body = "mnml's own request format — method, URL, headers, and body in one file. Opening it launches the Request pane UI instead of a plain-text editor." },
    .{ .key = "rest", .lang = "HTTP request file", .body = "mnml's own request format — method, URL, headers, and body in one file. Opening it launches the Request pane UI instead of a plain-text editor." },
    .{ .key = "request", .lang = "HTTP request file", .body = "mnml's own request format — method, URL, headers, and body in one file. Opening it launches the Request pane UI instead of a plain-text editor." },
    .{ .key = "cjs", .lang = "CommonJS module", .body = "Explicit CommonJS (`require` / `module.exports`) — same JS runtime as plain `.js`, but the extension forces CommonJS even inside a `\"type\": \"module\"` package. The TypeScript language server serves it like `.js`." },
    .{ .key = "mjs", .lang = "ES module", .body = "Explicit ES module (`import` / `export`) — the extension forces ESM even inside a package that defaults to CommonJS. The TypeScript language server serves it like `.js`." },
    .{ .key = "less", .lang = "Less stylesheet", .body = "Variables, nesting, and mixins that precompile to plain CSS. Syntax-only highlighting; no LSP." },
    .{ .key = "csv", .lang = "CSV data", .body = "Comma-separated tabular data. mnml renders it as plain text, not a spreadsheet grid — no column alignment or sorting." },
    .{ .key = "ini", .lang = "INI config", .body = "Key=value settings grouped into `[section]` blocks. No LSP; syntax-only highlighting." },
    .{ .key = "conf", .lang = "INI config", .body = "Key=value settings grouped into `[section]` blocks. No LSP; syntax-only highlighting." },
    .{ .key = "rb", .lang = "Ruby source", .body = "Ruby source file. Syntax-only highlighting; no LSP (solargraph isn't wired in yet)." },
    .{ .key = "php", .lang = "PHP source", .body = "PHP source file. Syntax-only highlighting; no LSP (intelephense isn't wired in yet)." },
    .{ .key = "lua", .lang = "Lua source", .body = "Lua source file. Syntax-only highlighting; no LSP." },
    .{ .key = "ps1", .lang = "PowerShell script", .body = "PowerShell script. Syntax-only highlighting; no LSP." },
    .{ .key = "txt", .lang = "Plain text", .body = "No syntax highlighting applied — mnml opens it exactly as written." },
    .{ .key = "lock", .lang = "Dependency lockfile", .body = "Pins exact resolved dependency versions (Cargo.lock-style). Generated by the package manager — hand-editing it is unusual and gets overwritten on the next install." },
    .{ .key = "log", .lang = "Log file", .body = "Append-only runtime output, not source. `Ctrl+F` (find) is usually the fastest way to jump around a large one." },
    .{ .key = "exe", .lang = "Windows executable", .body = "Binary Windows executable. mnml doesn't render binary content — opening it shows raw bytes, not source." },
    .{ .key = "dll", .lang = "Windows library", .body = "Binary Windows dynamic-link library. mnml doesn't render binary content — opening it shows raw bytes, not source." },
    .{ .key = "zip", .lang = "Compressed archive", .body = "mnml doesn't unpack it inline — extract with a terminal pane (`tar` / `unzip`) to browse the contents." },
    .{ .key = "gz", .lang = "Compressed archive", .body = "mnml doesn't unpack it inline — extract with a terminal pane (`tar` / `unzip`) to browse the contents." },
    .{ .key = "tgz", .lang = "Compressed archive", .body = "mnml doesn't unpack it inline — extract with a terminal pane (`tar` / `unzip`) to browse the contents." },
};

/// The curated entry for a tree row: a directory, a `.d.ts`, a known
/// filename, a known extension — else null.
pub fn rowEntry(arena: Allocator, label: []const u8, is_dir: bool) Allocator.Error!?Entry {
    if (is_dir) return .{
        .title = try std.fmt.allocPrint(arena, "{s}/", .{label}),
        .body = "Directory. Enter or click to expand; walk the tree with arrows or j/k. Right-click for rename / cut / copy / new file.",
        .keys = &dir_keys,
        .links = &.{ .{ .command = .{ .id = .@"file.new", .label = "New file here" } }, .{ .command = .{ .id = .@"files.open", .label = "Open as a Files pane" } } },
    };
    var buf: [256]u8 = undefined;
    if (label.len > buf.len) return null;
    const lower = std.ascii.lowerString(&buf, label);
    if (std.mem.endsWith(u8, lower, ".d.ts")) return .{
        .title = try std.fmt.allocPrint(arena, "{s} — TypeScript declarations", .{label}),
        .body = "`.d.ts` — TypeScript type declarations. No runtime code; describes the shape of a JS module for tsserver to consume. Editing here changes types, not behavior.",
        .keys = &open_keys,
        .links = &file_links,
    };
    for (by_name) |r| if (std.mem.eql(u8, r.key, lower)) return .{
        .title = try std.fmt.allocPrint(arena, "{s} — {s}", .{ label, r.lang }),
        .body = r.body,
        .keys = &open_keys,
        .links = &file_links,
    };
    const ext = icons.extensionOf(lower) orelse return null;
    for (by_ext) |r| if (std.mem.eql(u8, r.key, ext)) return .{
        .title = try std.fmt.allocPrint(arena, "{s} — {s}", .{ label, r.lang }),
        .body = r.body,
        .keys = &open_keys,
        .links = &file_links,
    };
    return null;
}

const file_links = [_]copy.Link{ .{ .command = .{ .id = .@"tree.open_selected", .label = "Open it" } }, .{ .command = .{ .id = .@"tree.open_in_split", .label = "Open in a split" } } };

/// The entry for a tree row, curated or the generic line — never null
/// for a row that exists, so the audit counts an unknown extension as
/// curated-by-family rather than a gap.
pub fn rowOrGeneric(arena: Allocator, name: []const u8, is_dir: bool) Allocator.Error!Entry {
    if (try rowEntry(arena, name, is_dir)) |e| return e;
    return .{
        .title = name,
        .body = "A file the dictionary has no words for yet — mnml opens it as text with the highlighter its extension maps to, or none. Enter opens it in a new tab; right-click for cut / copy / paste / rename; drag it onto a folder to move it.",
        .keys = &open_keys,
        .links = &file_links,
    };
}

pub fn node(app: *App, arena: Allocator, idx: u32) Allocator.Error!?Entry {
    if (idx >= app.tree.rows.items.len) return null;
    const row = app.tree.rows.items[idx];
    if (row.header) return try root(app, arena, 0);
    return try rowOrGeneric(arena, row.name(), row.is_dir);
}

pub fn root(app: *App, arena: Allocator, r: u8) Allocator.Error!?Entry {
    if (r == 0) return .{
        .title = "Workspace root",
        .body = "Names the folder the tree is rooted at — click to collapse or expand the whole tree, Alt+click to fold or open every directory. The chips on the row make a folder or a file, pull, fold every directory, and rescan. Right-click is the workspace menu: a new file or folder, add, switch or manage workspaces, copy the path, refresh.",
        .keys = &.{.{ .chord = "Alt+click", .label = "Fold / open every directory" }},
        .links = &.{ .{ .command = .{ .id = .@"view.add_workspace", .label = "Add a workspace root" } }, .{ .command = .{ .id = .@"view.switch_workspace", .label = "Switch workspace" } } },
    };
    if (r - 1 < app.tree.roots.items.len) return .{
        .title = try std.fmt.allocPrint(arena, "Workspace: {s}", .{app.tree.roots.items[r - 1].name}),
        .body = "An extra workspace root from `workspaces` in config.zon, as a second section of the tree. Click to open or fold its tree; `view.switch_workspace` makes it the one open, with its own session and `.mnml/`. Its files open like any other; git follows the repo they are in.",
        .keys = &.{ .{ .chord = "Enter", .label = "Open / fold the section" }, .{ .command = .@"view.switch_workspace", .label = "Make it the workspace" } },
        .links = &.{ .{ .command = .{ .id = .@"view.switch_workspace", .label = "Switch to it" } }, .{ .command = .{ .id = .@"view.remove_workspace", .label = "Remove a root" } } },
    };
    return null;
}

pub fn empty() Entry {
    return .{
        .title = "Workspace — the empty rows",
        .body = "The tree's rows below the last file. A click here focuses the tree without picking a row; right-click opens the workspace menu — a new file or folder at the root, add, switch or manage workspaces — the same rows the root's header offers. Drop a file here to move it to the root.",
        .keys = &.{ .{ .chord = "Right-click", .label = "The workspace menu" }, .{ .command = .@"file.new", .label = "New file at the root" } },
        .links = &.{ .{ .command = .{ .id = .@"file.new", .label = "New file" } }, .{ .command = .{ .id = .@"file.new_folder", .label = "New folder" } } },
    };
}

/// A header chip's copy (Rust `TreeIcon`), with a `Run it` link.
pub fn chip(c: tree_view.Chip) Entry {
    return switch (c) {
        inline else => |cc| chipEntry(cc),
    };
}

/// The chip's entry with `id` comptime-known, so the links array is
/// static data rather than a stack temporary the caller would outlive.
fn chipEntry(comptime c: tree_view.Chip) Entry {
    const id = comptime tree_mod.chipCommand(c);
    return switch (c) {
        .new_file => .{ .title = "New file", .body = "Creates an empty file in the workspace root and opens it in a fresh tab, prompting for a name first. A name with a slash makes the folders on the way; a name that exists opens that file instead.", .links = &.{ .{ .command = .{ .id = id, .label = "Run it" } }, .{ .command = .{ .id = .@"file.new_folder", .label = "New folder instead" } } } },
        .new_folder => .{ .title = "New folder", .body = "Creates a new directory in the workspace root after prompting for a name. The tree jumps to show it; a name with a slash makes every folder on the way.", .links = &.{ .{ .command = .{ .id = id, .label = "Run it" } }, .{ .command = .{ .id = .@"file.new", .label = "New file instead" } } } },
        .refresh => .{ .title = "Refresh tree", .body = "Re-scans the workspace root from disk and repaints the tree — use it after external changes mnml's file-watcher might have missed (bulk git operations, another process writing files). Open folders stay open; the cursor stays on its row when the row survives.", .links = &.{ .{ .command = .{ .id = id, .label = "Run it" } }, .{ .command = .{ .id = .@"git.refresh", .label = "Refresh git too" } } } },
        .collapse => .{ .title = "Collapse / expand all", .body = "Folds every open directory in the tree closed, or opens every directory when the tree is already fully collapsed. One click toggles the whole rail; the chip's glyph says which way the next click goes.", .links = &.{ .{ .command = .{ .id = id, .label = "Run it" } }, .{ .command = .{ .id = .@"tree.expand_all", .label = "Expand every directory" } } } },
        .pull => .{ .title = "Pull (workspace header)", .body = "Runs `git pull --ff-only` against the repo that owns this workspace root, right from the tree header, and toasts the result. A pull that would need a merge stops and says so — the git palette's rows are where the merge happens.", .links = &.{ .{ .command = .{ .id = id, .label = "Run it" } }, .{ .command = .{ .id = .@"git.push", .label = "Push" } }, ask } },
        .add_workspace => .{ .title = "Add workspace folder", .body = "Opens a path prompt to add another folder as an extra workspace root alongside the current one — the tree grows a second top-level section instead of replacing what's open. Type a path (`~` expands); missing intermediate folders are NOT created here. The root is written to `workspaces` in config.zon.", .links = &.{ .{ .command = .{ .id = id, .label = "Run it" } }, .{ .command = .{ .id = .@"view.manage_workspaces", .label = "Manage the workspaces" } } } },
    };
}

// ─── tests ──────────────────────────────────────────────────────────────

const t = std.testing;

test "the dictionary: a directory, package.json, a .d.ts, a plain .txt, and an unknown extension" {
    var arena_state: std.heap.ArenaAllocator = .init(t.allocator);
    defer arena_state.deinit();
    const a = arena_state.allocator();
    const dir = (try rowEntry(a, "src", true)).?;
    try t.expectEqualStrings("src/", dir.title);
    try t.expectEqual(@as(usize, 2), dir.keys.len);
    try t.expectEqualStrings("Enter", dir.keys[0].chord);
    const pkg = (try rowEntry(a, "Package.JSON", false)).?;
    try t.expectEqualStrings("Package.JSON — npm manifest", pkg.title);
    const dts = (try rowEntry(a, "types.d.ts", false)).?;
    try t.expectEqualStrings("types.d.ts — TypeScript declarations", dts.title);
    const txt = (try rowEntry(a, "notes.txt", false)).?;
    try t.expectEqualStrings("notes.txt — Plain text", txt.title);
    // `tree.open_in_split` has no chord in either profile, so the row
    // names only Enter — the split is the row menu's *Open in split*.
    try t.expectEqual(@as(usize, 1), txt.keys.len);
    try t.expect((try rowEntry(a, "weird.xyz", false)) == null);
    try t.expectEqualStrings("weird.xyz", (try rowOrGeneric(a, "weird.xyz", false)).title);
    try t.expect((try rowEntry(a, "Makefile", false)) != null);
    // Every dictionary key is lower-case and unique within its table.
    inline for (.{ by_name, by_ext }) |table| for (table, 0..) |r, i| {
        for (r.key) |c| try t.expect(!std.ascii.isUpper(c));
        for (table[0..i]) |prev| try t.expect(!std.mem.eql(u8, prev.key, r.key));
        try t.expect(r.body.len > 20);
    };
    // Every chip has an entry with its command as the first link.
    inline for (comptime std.enums.values(tree_view.Chip)) |c| try t.expectEqual(tree_mod.chipCommand(c), chip(c).links[0].command.id);
}
