//! `mnml-vt-sys` — raw FFI bindings to Ghostty's [libghostty-vt] C ABI.
//!
//! The upstream C headers are vendored under `vendor/libghostty-vt/` at the
//! workspace root; bindings are generated by `bindgen` at build time (see
//! `build.rs`). Linking goes through pkg-config against a prebuilt static
//! `.a` (also under `vendor/libghostty-vt/`), so no Zig toolchain is needed
//! on the host — Ghostty pins Zig 0.15.2, which can't link on macOS 26.
//!
//! This crate exposes the C API essentially verbatim. Ergonomic wrappers
//! (safe iterators, typed handles, RAII destruction) live in the
//! [`mnml-vt`] sibling crate — mnml core depends on that one, not this.
//!
//! [libghostty-vt]: https://github.com/ghostty-org/ghostty/tree/main/include/ghostty

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
