name = "ayu_light"
type = "light"   # dark | light
# credit to original theme for existing https://github.com/ayu-theme/ayu-vim (light)
# NOTE : This is a modified version of it

[base_30]
white = "#26292f"
darker_black = "#f3f3f3"
black = "#fafafa"
black2 = "#efefef"
one_bg = "#ebebeb"
one_bg2 = "#e1e1e1"
one_bg3 = "#d7d7d7"
grey = "#cdcdcd"
grey_fg = "#b9b9b9"
grey_fg2 = "#acacac"
light_grey = "#a0a0a0"
red = "#e65050"
baby_pink = "#ff8282"
pink = "#ffa5a5"
line = "#e1e1e1"
green = "#6cbf43"
vibrant_green = "#94e76b"
blue = "#399ee6"
nord_blue = "#2c91d9"
yellow = "#e6ba7e"
sun = "#f3c78b"
purple = "#9f40ff"
dark_purple = "#8627e6"
teal = "#74c5aa"
orange = "#fa8d3e"
cyan = "#95e6cb"
statusline_bg = "#f0f0f0"
lightbg = "#e6e6e6"
pmenu_bg = "#95e6cb"
folder_bg = "#5c6166"

[base_16]
base00 = "#fafafa"
base01 = "#f0f0f0"
base02 = "#eeeeee"
base03 = "#dfdfdf"
base04 = "#d2d2d2"
base05 = "#5c6166"
base06 = "#52575c"
base07 = "#484d52"
base08 = "#f07171"
base09 = "#a37acc"
base0A = "#399ee6"
base0B = "#86b300"
base0C = "#4cbf99"
base0D = "#55b4d4"
base0E = "#fa8d3e"
base0F = "#f2ae49"
