name = "bearded-arc"
type = "dark"   # dark | light
# credits to original theme for existing https://github.com/BeardedBear/bearded-theme ( arc version )
# This is just a modified version of it

[base_30]
white = "#abb7c1"
darker_black = "#19212e"
black = "#1c2433"
black2 = "#232b3a"
one_bg = "#262e3d"
one_bg2 = "#303847"
one_bg3 = "#3a4251"
grey = "#444c5b"
grey_fg = "#4e5665"
grey_fg2 = "#58606f"
light_grey = "#626a79"
red = "#ff738a"
baby_pink = "#f38cec"
pink = "#ee9cdd"
line = "#303847"
green = "#3cec85"
vibrant_green = "#9bdead"
nord_blue = "#6da4cd"
blue = "#69c3ff"
yellow = "#eacd61"
sun = "#f6d96d"
purple = "#bd93ff"
dark_purple = "#b78aff"
teal = "#12c7c4"
orange = "#ff955c"
cyan = "#22ecdb"
statusline_bg = "#232b3a"
lightbg = "#303847"
pmenu_bg = "#3cec85"
folder_bg = "#69c3ff"

[base_16]
base00 = "#1c2433"
base01 = "#262e3d"
base02 = "#303847"
base03 = "#444c5b"
base04 = "#a1adb7"
base05 = "#c3cfd9"
base06 = "#abb7c1"
base07 = "#08bdba"
base08 = "#ff738a"
base09 = "#ff955c"
base0A = "#eacd61"
base0B = "#3cec85"
base0C = "#77aed7"
base0D = "#69c3ff"
base0E = "#22ecdb"
base0F = "#b78aff"
