name = "carbonfox"
type = "dark"   # dark | light

[base_30]
white = "#dfdfe0"
black = "#161616"
darker_black = "#0e0e0e"
black2 = "#1d1d1d"
one_bg = "#242424"
one_bg2 = "#2b2b2b"
one_bg3 = "#323232"
grey = "#404040"
grey_fg = "#4e4e4e"
grey_fg2 = "#5c5c5c"
light_grey = "#636363"
red = "#ee5396"
baby_pink = "#ff7eb6"
pink = "#ff7eb6"
line = "#2a2a2a"
green = "#25be6a"
vibrant_green = "#42be65"
nord_blue = "#78a9ff"
blue = "#78a9ff"
yellow = "#ffe731"
sun = "#ffe731"
purple = "#be95ff"
dark_purple = "#9b69d9"
teal = "#33b1ff"
orange = "#ffa332"
cyan = "#3ddbd9"
statusline_bg = "#1d1d1d"
lightbg = "#2b2b2b"
pmenu_bg = "#08bdba"
folder_bg = "#78a9ff"

[base_16]
base00 = "#161616"
base01 = "#282828"
base02 = "#2a2a2a"
base03 = "#3b3b3b"
base04 = "#525253"
base05 = "#f2f4f8"
base06 = "#e0e0e0"
base07 = "#ffffff"
base08 = "#78a9ff"
base09 = "#08bdba"
base0A = "#3ddbd9"
base0B = "#25be6a"
base0C = "#33b1ff"
base0D = "#ff7eb6"
base0E = "#be95ff"
base0F = "#78a9ff"
