name = "catppuccin-latte"
type = "light"   # dark | light

[base_30]
white = "#7287fd"
darker_black = "#e6e9ef"
black = "#eff1f5"
black2 = "#dbdfe9"
one_bg = "#d1d6e3"
one_bg2 = "#c7cddd"
one_bg3 = "#bdc4d7"
grey = "#b3bbd1"
grey_fg = "#a9b2cb"
grey_fg2 = "#9fa9c5"
light_grey = "#8b97b9"
red = "#e64553"
baby_pink = "#dd7878"
pink = "#ea76cb"
line = "#d4d6dc"
green = "#40a02b"
vibrant_gree = "#179299"
nord_blue = "#1e66f5"
blue = "#04a5e5"
yellow = "#df8e1d"
sun = "#dfaf1d"
purple = "#8839ef"
dark_purple = "#dd7878"
teal = "#179299"
orange = "#fe640b"
cyan = "#209fb5"
statusline_bg = "#dce0e8"
lightbg = "#d0d5df"
pmenu_bg = "#6c6e83"
folder_bg = "#666983"

[base_16]
base00 = "#eff1f5"
base01 = "#e5e8ef"
base02 = "#dbdfe9"
base03 = "#c3c7d3"
base04 = "#b3b7c5"
base05 = "#4c4f69"
base06 = "#5c5f77"
base07 = "#6c6f85"
base08 = "#e64553"
base09 = "#fe640b"
base0A = "#df8e1d"
base0B = "#40a02b"
base0C = "#04a5e5"
base0D = "#1e66f5"
base0E = "#8839ef"
base0F = "#fe640b"
