name = "chadracula-evondev"
type = "dark"   # dark | light
# Credits to original theme https://github.com/evondev/evondev-dracula
# This is a modified version

[base_30]
white = "#f8f8f2"
darker_black = "#19192c"
black = "#141423"
black2 = "#1c1c31"
one_bg = "#23233d"
one_bg2 = "#2b2b4c"
one_bg3 = "#373760"
grey = "#414171"
grey_fg = "#4b4b83"
grey_fg2 = "#555594"
light_grey = "#6060a4"
red = "#ff5555"
baby_pink = "#ff6e6e"
pink = "#ff6bcb"
line = "#2d2d4e"
green = "#50fa7b"
vibrant_green = "#20e3b2"
nord_blue = "#05c3ff"
blue = "#2cccff"
yellow = "#f1fa8c"
sun = "#f2fa95"
purple = "#bd93f9"
dark_purple = "#a166f6"
teal = "#92a2d4"
orange = "#ffb86c"
cyan = "#2cccff"
statusline_bg = "#19192c"
lightbg = "#2b2b4c"
pmenu_bg = "#9a86fd"
folder_bg = "#9a86fd"
violet = "#9a86fd"
darkgreen = "#1b312e"
brownred = "#5d2932"

[base_16]
base00 = "#141423"
base05 = "#e9e9f4"
base06 = "#f1f2f8"
base07 = "#f7f7fb"
base08 = "#c197fd"
base09 = "#ffb86c"
base0A = "#62d6e8"
base0B = "#e5c697"
base0C = "#8be9fd"
base0D = "#20e3b2"
base0E = "#ff6bcb"
base0F = "#7e7eb5"
