name = "eldritch"
type = "dark"   # dark | light
# Credits to the original authors of [Eldritch](https://github.com/eldritch-theme/eldritch)
# This is just a port for NvChad's theme engine: base46
# @class Base46Table

[base_30]
white = "#ebfafa"
darker_black = "#131421"
black = "#171928"
black2 = "#202338"
one_bg = "#292d48"
one_bg2 = "#323758"
one_bg3 = "#323758"
grey = "#444b78"
grey_fg = "#4d5588"
grey_fg2 = "#4c5488"
light_grey = "#6770aa"
red = "#f16c75"
baby_pink = "#f265b5"
pink = "#bf4f8e"
line = "#3b4261"
green = "#37f499"
vibrant_green = "#00fa82"
nord_blue = "#7081d0"
blue = "#04d1f9"
yellow = "#f1fc79"
sun = "#e9f941"
purple = "#a48cf2"
dark_purple = "#5866a2"
teal = "#33c57f"
orange = "#f7c67f"
cyan = "#04d1f9"
statusline_bg = "#1e2134"
lightbg = "#292d48"
pmenu_bg = "#37f499"
folder_bg = "#66e4fd"

[base_16]
base00 = "#171928"
base01 = "#21253a"
base02 = "#262b43"
base03 = "#3b4261"
base04 = "#8386a8"
base05 = "#abb4da"
base06 = "#ebfafa"
base07 = "#ffffff"
base08 = "#f16c75"
base09 = "#f16c75"
base0A = "#f7c67f"
base0B = "#f1fc79"
base0C = "#04d1f9"
base0D = "#7081d0"
base0E = "#a48cf2"
base0F = "#f16c75"
