name = "flouromachine"
type = "dark"   # dark | light

[base_30]
white = "#ffffff"
black = "#262335"
darker_black = "#1f1c2b"
black2 = "#2c293e"
one_bg = "#322f47"
one_bg2 = "#383550"
one_bg3 = "#3e3b59"
grey = "#4a476b"
grey_fg = "#545076"
grey_fg2 = "#5a567f"
light_grey = "#605c88"
red = "#fe4450"
baby_pink = "#fc199a"
pink = "#fe4450"
line = "#383550"
green = "#72f1b8"
vibrant_green = "#72f1b8"
nord_blue = "#61e2ff"
blue = "#61e2ff"
yellow = "#ffcc00"
sun = "#ffcc00"
purple = "#af6df9"
dark_purple = "#af6df9"
teal = "#61e2ff"
orange = "#ff8b39"
cyan = "#61e2ff"
statusline_bg = "#2c293e"
lightbg = "#322f47"
pmenu_bg = "#72f1b8"
folder_bg = "#61e2ff"

[base_16]
base00 = "#262335"
base01 = "#322f47"
base02 = "#3e3b59"
base03 = "#4a476b"
base04 = "#56537d"
base05 = "#61e2ff"
base06 = "#dbe3e3"
base07 = "#ffffff"
base08 = "#61e2ff"
base09 = "#72f1b8"
base0A = "#fc199a"
base0B = "#b77bf9"
base0C = "#ff8b39"
base0D = "#ffcc00"
base0E = "#fc199a"
base0F = "#40dbfc"
