name = "horizon"
type = "dark"   # dark | light
# Credits and reference: https://github.com/LunarVim/horizon.nvim

[base_30]
white = "#d5d8da"
black = "#1d1f27"
darker_black = "#16181e"
black2 = "#282b36"
one_bg = "#2f3340"
one_bg2 = "#393d4d"
one_bg3 = "#43485b"
grey = "#4f546b"
grey_fg = "#5b607b"
grey_fg2 = "#676c8b"
light_grey = "#757b99"
red = "#e95678"
baby_pink = "#ff007c"
pink = "#f43e5c"
line = "#3b3c41"
green = "#27d796"
vibrant_green = "#21bfc2"
nord_blue = "#75beff"
blue = "#25b2bc"
yellow = "#fac29a"
sun = "#fab795"
purple = "#b877db"
dark_purple = "#b180d7"
teal = "#21bfc2"
orange = "#f09383"
cyan = "#25b2bc"
statusline_bg = "#21242d"
lightbg = "#2d323d"
pmenu_bg = "#fab795"
folder_bg = "#e95678"

[base_16]
base00 = "#1d1f27"
base01 = "#4b4c53"
base02 = "#3a324a"
base03 = "#4b4c53"
base04 = "#8b8d8f"
base05 = "#d5d8da"
base06 = "#c8ccd4"
base07 = "#6c6f93"
base08 = "#8a8c8e"
base09 = "#fab795"
base0A = "#fabd2f"
base0B = "#21bfc2"
base0C = "#b877db"
base0D = "#59c2ff"
base0E = "#b877db"
base0F = "#f09383"
