name = "material-lighter"
type = "light"   # dark | light
# Credits to original theme https://github.com/marko-cerovac/material.nvim for existing
# This is a modified version of it

[base_30]
white = "#435862"
darker_black = "#f2f2f2"
black = "#fafafa"
black2 = "#ebebeb"
one_bg = "#ebebeb"
one_bg2 = "#e1e1e1"
one_bg3 = "#d9d9d9"
grey = "#c4c4c4"
grey_fg = "#c4c4c4"
grey_fg2 = "#bdbdbd"
light_grey = "#b3b3b3"
red = "#e53935"
baby_pink = "#ff5370"
pink = "#ff5370"
line = "#ebebeb"
green = "#91b859"
vibrant_green = "#a7c67a"
nord_blue = "#4e73ae"
blue = "#6182b8"
yellow = "#f59717"
sun = "#f6a434"
purple = "#7c4dff"
dark_purple = "#9671ff"
teal = "#39adb5"
orange = "#f76d47"
cyan = "#39adb5"
statusline_bg = "#f2f2f2"
lightbg = "#e7e7e8"
pmenu_bg = "#00bcd4"
folder_bg = "#6e98eb"

[base_16]
base00 = "#fafafa"
base01 = "#eeeeee"
base02 = "#e7e7e8"
base03 = "#d2d4d5"
base04 = "#c4c4c4"
base05 = "#435862"
base06 = "#7e8eaa"
base07 = "#546e7a"
base09 = "#f76d47"
base0A = "#00bcd4"
base0B = "#91b859"
base0C = "#39adb5"
base0D = "#6182b8"
base0E = "#7c4dff"
base0F = "#e53935"
