name = "melange"
type = "dark"   # dark | light
# Thanks to https://github.com/savq/melange for existing
# This is a modified version of it

[base_30]
white = "#ece1d7"
darker_black = "#241f1a"
black = "#2a2520"
black2 = "#342f2a"
one_bg = "#39342f"
one_bg2 = "#433e39"
one_bg3 = "#4d4843"
grey = "#57524d"
grey_fg = "#605b56"
grey_fg2 = "#6b6661"
light_grey = "#75706b"
red = "#b65c60"
baby_pink = "#ce9bcb"
pink = "#b65c60"
line = "#39342f"
green = "#86a3a3"
vibrant_green = "#99d59d"
nord_blue = "#88b3b2"
blue = "#9aacce"
yellow = "#e3b865"
sun = "#ebc06d"
purple = "#c47fd5"
dark_purple = "#b570c6"
teal = "#697893"
orange = "#e49b5d"
firered = "#f17c64"
cyan = "#bbcdef"
statusline_bg = "#312c27"
lightbg = "#433e39"
pmenu_bg = "#86a3a3"
folder_bg = "#697893"

[base_16]
base00 = "#2a2520"
base01 = "#39342f"
base02 = "#433e39"
base03 = "#4d4843"
base04 = "#57524d"
base05 = "#ece1d7"
base06 = "#e3d8ce"
base07 = "#d8cdc3"
base08 = "#ece1d7"
base09 = "#86a3a3"
base0A = "#99d59d"
base0B = "#9aacce"
base0C = "#ebc06d"
base0D = "#ebc06d"
base0E = "#e49b5d"
base0F = "#8e733f"
