name = "penumbra_dark"
type = "dark"   # dark | light
# credits to original theme for existing https://github.com/nealmckee/penumbra
# This is a modified version of it

[base_30]
white = "#fffdfb"
darker_black = "#2b2e33"
black = "#303338"
black2 = "#3a3d42"
one_bg = "#3d4045"
one_bg2 = "#484b50"
one_bg3 = "#515459"
grey = "#5c5f64"
grey_fg = "#676a6f"
grey_fg2 = "#72757a"
light_grey = "#7d8085"
red = "#ca7081"
baby_pink = "#e18163"
pink = "#d07eba"
green = "#4eb67f"
vibrant_green = "#50b584"
nord_blue = "#6e8dd5"
blue = "#8c96ec"
yellow = "#c1ad4b"
sun = "#9ca748"
purple = "#ac78bd"
dark_purple = "#8c96ec"
orange = "#ce9042"
teal = "#00a6c8"
cyan = "#00b3c2"
line = "#3e4044"
statusline_bg = "#34373c"
lightbg = "#484b50"
pmenu_bg = "#4eb67f"
folder_bg = "#8c96ec"

[base_16]
base00 = "#303338"
base01 = "#3a3d42"
base02 = "#3d4045"
base03 = "#484b50"
base04 = "#515459"
base05 = "#cecece"
base06 = "#f2e6d4"
base07 = "#fff7ed"
base08 = "#999999"
base09 = "#be85d1"
base0A = "#ca7081"
base0B = "#4ec093"
base0C = "#d68b47"
base0D = "#7a9bec"
base0E = "#be85d1"
base0F = "#a1a641"
