name = "penumbra_light"
type = "light"   # dark | light
# credits to original theme for existing https://github.com/nealmckee/penumbra
# this is a modified version of it

[base_30]
white = "#3e4044"
light_grey = "#b0a89e"
grey_fg2 = "#bab2a8"
grey_fg = "#c4bcb2"
grey = "#cec6bc"
one_bg3 = "#dad2c8"
one_bg2 = "#e6ded4"
black2 = "#f0e8de"
one_bg = "#f2e6d4"
black = "#fff7ed"
darker_black = "#f5ede3"
baby_pink = "#ca736c"
blue = "#6e8dd5"
cyan = "#00a0ba"
dark_purple = "#806db8"
green = "#3ea57b"
nord_blue = "#5794d0"
orange = "#ba823a"
pink = "#ca7081"
purple = "#ac78bd"
red = "#ca7081"
sun = "#a38f2d"
teal = "#22839b"
vibrant_green = "#46a473"
yellow = "#92963a"
line = "#ebe3d9"
statusline_bg = "#f5ede3"
lightbg = "#e6ded4"
pmenu_bg = "#ac78bd"
folder_bg = "#717171"
coal = "#8a8a8a"

[base_16]
base00 = "#fff7ed"
base01 = "#fff7ed"
base02 = "#f2e6d4"
base03 = "#cecece"
base04 = "#9e9e9e"
base05 = "#636363"
base06 = "#3e4044"
base07 = "#24272b"
base08 = "#ca7081"
base09 = "#5a79c1"
base0A = "#ba823a"
base0B = "#3ea57b"
base0C = "#22839b"
base0D = "#4380bc"
base0E = "#ac78bd"
base0F = "#ca7081"
