name = "rosepine-dawn"
type = "light"   # dark | light
# credits to original theme https://rosepinetheme.com/
# this is a modified version of it
# @type Base46Table

[base_30]
white = "#575279"
black = "#faf4ed"
darker_black = "#f2e9e1"
black2 = "#ede1d6"
one_bg = "#eadccf"
one_bg2 = "#e4d2c1"
one_bg3 = "#dec7b3"
grey = "#b0acb9"
grey_fg = "#a39ead"
grey_fg2 = "#9893a4"
light_grey = "#908b9d"
red = "#b4637a"
baby_pink = "#eb6f92"
pink = "#eb6f92"
line = "#eadccf"
green = "#286983"
vibrant_green = "#3e8fb0"
nord_blue = "#459bbd"
blue = "#56949f"
yellow = "#ea9d34"
sun = "#f6c177"
purple = "#907aa9"
dark_purple = "#c4a7e7"
teal = "#3e8fb0"
orange = "#ea9d34"
cyan = "#d7827e"
statusline_bg = "#f2e9e1"
lightbg = "#eadccf"
pmenu_bg = "#907aa9"
folder_bg = "#56949f"

[base_16]
base00 = "#faf4ed"
base01 = "#fffaf3"
base02 = "#f2e9e1"
base03 = "#9893a5"
base04 = "#797593"
base05 = "#575279"
base06 = "#423e5b"
base07 = "#dfdad9"
base08 = "#b4637a"
base09 = "#ea9d34"
base0A = "#d7827e"
base0B = "#56949f"
base0C = "#286983"
base0D = "#907aa9"
base0E = "#ea9d34"
base0F = "#a39ead"
