name = "rxyhn"
type = "dark"   # dark | light
# credits to rice made by https://github.com/rxyhn
# This theme is made for @rxyhn's rice :D

[base_30]
white = "#d9d7d6"
darker_black = "#000a0e"
black = "#061115"
black2 = "#0d181c"
one_bg = "#131e22"
one_bg2 = "#1c272b"
one_bg3 = "#242f33"
grey = "#313c40"
grey_fg = "#3b464a"
grey_fg2 = "#455054"
light_grey = "#4f5a5e"
red = "#df5b61"
baby_pink = "#ee6a70"
pink = "#f16269"
line = "#222d31"
green = "#78b892"
vibrant_green = "#8cd7aa"
nord_blue = "#5a84bc"
blue = "#6791c9"
yellow = "#ecd28b"
sun = "#f6dc95"
purple = "#c488ec"
dark_purple = "#bc83e3"
teal = "#7acfe4"
orange = "#e89982"
cyan = "#67afc1"
statusline_bg = "#0a1519"
lightbg = "#1a2529"
pmenu_bg = "#78b892"
folder_bg = "#6791c9"

[base_16]
base00 = "#061115"
base01 = "#0c171b"
base02 = "#101b1f"
base03 = "#192428"
base04 = "#212c30"
base05 = "#d9d7d6"
base06 = "#e3e1e0"
base07 = "#edebea"
base08 = "#f26e74"
base09 = "#ecd28b"
base0A = "#e9967e"
base0B = "#82c29c"
base0C = "#6791c9"
base0D = "#79aaeb"
base0E = "#c488ec"
base0F = "#f16269"
