name = "seoul256_light"
type = "light"   # dark | light

[base_30]
white = "#4e4e4e"
darker_black = "#d7d7d7"
black = "#e0e0e0"
black2 = "#d0d0d0"
one_bg = "#c8c8c8"
one_bg2 = "#c0c0c0"
one_bg3 = "#b8b8b8"
grey = "#b0b0b0"
grey_fg = "#a8a8a8"
grey_fg2 = "#a0a0a0"
light_grey = "#989898"
red = "#af5f5f"
baby_pink = "#d0a39f"
pink = "#875f87"
line = "#c8c8c8"
green = "#5f885f"
vibrant_green = "#93b2b2"
blue = "#5f87ae"
nord_blue = "#7395b8"
yellow = "#af8760"
sun = "#d8865f"
purple = "#875f87"
dark_purple = "#875f87"
teal = "#5f8787"
orange = "#af8760"
cyan = "#008787"
statusline_bg = "#d8d8d8"
lightbg = "#c8c8c8"
pmenu_bg = "#67a9aa"
folder_bg = "#6a6a6a"

[base_16]
base00 = "#e4e4e4"
base01 = "#d0d0d0"
base02 = "#c8c8c8"
base03 = "#c0c0c0"
base04 = "#b0b0b0"
base05 = "#4e4e4e"
base06 = "#555555"
base07 = "#5c5c5c"
base08 = "#6a6a6a"
base09 = "#678e8e"
base0A = "#af8760"
base0B = "#5f885f"
base0C = "#67a9aa"
base0D = "#5f87ae"
base0E = "#875f87"
base0F = "#d8865f"
