name = "seoul256_dark"
type = "dark"   # dark | light

[base_30]
white = "#dfe0e0"
darker_black = "#444444"
black = "#4a4a4a"
black2 = "#515151"
one_bg = "#585858"
one_bg2 = "#5f5f5f"
one_bg3 = "#666666"
grey = "#6d6d6d"
grey_fg = "#747474"
grey_fg2 = "#7b7b7b"
light_grey = "#828282"
red = "#df9a98"
baby_pink = "#ffbeb0"
pink = "#dfbdbc"
line = "#606060"
green = "#719672"
vibrant_green = "#97bb98"
blue = "#96bbdc"
nord_blue = "#badcfc"
yellow = "#e0bb71"
sun = "#ffdd98"
purple = "#dfbdbc"
dark_purple = "#ffbeb0"
teal = "#7fb7bd"
orange = "#ffcb88"
cyan = "#96ddde"
statusline_bg = "#515151"
lightbg = "#5f5f5f"
pmenu_bg = "#d8d8d8"
folder_bg = "#67a9aa"
brown = "#a2a2a2"

[base_16]
base00 = "#4a4a4a"
base01 = "#515151"
base02 = "#585858"
base03 = "#5f5f5f"
base04 = "#666666"
base05 = "#d8d8d8"
base06 = "#d8d8d8"
base07 = "#dfe0e0"
base08 = "#df9a98"
base09 = "#e07798"
base0A = "#e0bb71"
base0B = "#97bb98"
base0C = "#97bcbc"
base0D = "#96bbdc"
base0E = "#dfbdbc"
base0F = "#b0b0b0"
