name = "tundra"
type = "dark"   # dark | light
# Thanks to original theme for existing https://github.com/sam4llis/nvim-tundra
# this is a modified version of it

[base_30]
white = "#ffffff"
darker_black = "#0b1221"
black = "#111827"
black2 = "#1a2130"
one_bg = "#1e2534"
one_bg2 = "#282f3e"
one_bg3 = "#323948"
grey = "#3e4554"
grey_fg = "#4a5160"
grey_fg2 = "#545b6a"
light_grey = "#5f6675"
red = "#fca5a5"
baby_pink = "#fecdd3"
pink = "#ff8e8e"
line = "#282f3e"
green = "#b5e8b0"
vibrant_green = "#b5e8b0"
nord_blue = "#9baaf2"
blue = "#a5b4fc"
yellow = "#e8d4b0"
sun = "#f2deba"
purple = "#bdb0e4"
dark_purple = "#b3a6da"
teal = "#719bd3"
orange = "#fbc19d"
cyan = "#bae6fd"
statusline_bg = "#171e2d"
lightbg = "#282f3e"
pmenu_bg = "#fca5a5"
folder_bg = "#a5b4fc"

[base_16]
base00 = "#111827"
base01 = "#1e2534"
base02 = "#282f3e"
base03 = "#323948"
base04 = "#3e4554"
base05 = "#f3f4f6"
base06 = "#e5e7eb"
base07 = "#d1d5db"
base08 = "#ddd6fe"
base09 = "#e8d4b0"
base0A = "#fbc19d"
base0B = "#b5e8b0"
base0C = "#bae6fd"
base0D = "#bae6fd"
base0E = "#fca5a5"
base0F = "#9ca3af"
