#!/usr/bin/env bash
# ui-diff — run the Rust and Zig binaries headless on one workspace with
# the same config, dump both screens, print a row-by-row diff.
#   ui-diff.sh [--no-copy] WS RS_DATA ZIG_DATA [STEPS_FILE] [COLSxROWS]
# STEPS_FILE: optional JSONL of IPC commands sent to BOTH after start.
#
# By default every run works on its own private copy of WS / RS_DATA /
# ZIG_DATA under a fresh `mktemp -d`, so any number of runs (several
# agents on the shared chrome fixture) can go at once: each editor
# reads its IPC command file and writes its session under the copy's
# `.mnml/`, never the caller's. Every absolute path inside the copied
# files that names one of the three source directories is rewritten to
# the copy's realpath (the Zig side compares the workspace's realpath
# with the one `session.zon` names, so `/tmp/x` would not match its own
# `/private/tmp/x`), and a grep afterwards proves none is left. The
# copy is deleted at exit; KEEP=1 keeps it and prints its path.
#
# --no-copy drives the caller's directories in place (the old
# behaviour): the session files are snapshotted before each editor
# starts and restored after, so a STEPS file that opens a file is not
# restored by the next run. Two in-place runs on the same paths cross-
# talk — one run's keystrokes land in the other's screen.
#
# Env: MNML_RUST_BIN / MNML_ZIG_BIN pick the binaries, OUT the output
# directory (default: a mktemp dir), KEEP=1 keeps the private copy.
set -u
COPY=1
while [ $# -gt 0 ]; do
  case $1 in
    --no-copy) COPY=0; shift ;;
    --copy) COPY=1; shift ;;
    --) shift; break ;;
    -*) echo "ui-diff: unknown option $1" >&2; exit 64 ;;
    *) break ;;
  esac
done
[ $# -ge 3 ] || { echo "usage: ui-diff.sh [--no-copy] WS RS_DATA ZIG_DATA [STEPS_FILE] [COLSxROWS]" >&2; exit 64; }
WS=$1; RS=$2; ZG=$3; STEPS=${4:-}; SIZE=${5:-120x40}
COLS=${SIZE%x*}; ROWS=${SIZE#*x}
RUST=${MNML_RUST_BIN:-/Users/chrismclennan/Projects/mnml/target/debug/mnml}
ZIG=${MNML_ZIG_BIN:-$(cd "$(dirname "$0")/.." && pwd)/zig-out/bin/mnml-zig}
OUT=${OUT:-$(mktemp -d)}; mkdir -p "$OUT"
[ -d "$WS" ] && [ -d "$RS" ] && [ -d "$ZG" ] || { echo "ui-diff: WS / RS_DATA / ZIG_DATA must be directories" >&2; exit 64; }
[ -z "$STEPS" ] || [ -f "$STEPS" ] || { echo "ui-diff: no steps file: $STEPS" >&2; exit 64; }

abs()  { (cd "$1" && pwd); }        # absolute, symlinks kept
real() { (cd "$1" && pwd -P); }     # the realpath — what the editors compare

SESSION_BAK=
save_session()    { [ -n "$SESSION_BAK" ] || return 0; rm -rf "$SESSION_BAK"/*; for f in "$WS"/.mnml/session*; do [ -e "$f" ] && cp -R "$f" "$SESSION_BAK/"; done; return 0; }
restore_session() { [ -n "$SESSION_BAK" ] || return 0; rm -rf "$WS"/.mnml/session*; cp -R "$SESSION_BAK"/. "$WS/.mnml/" 2>/dev/null; return 0; }

COPY_DIR=
cleanup() {
  [ -n "$SESSION_BAK" ] && rm -rf "$SESSION_BAK"
  if [ -n "$COPY_DIR" ]; then
    if [ "${KEEP:-0}" = 1 ]; then echo "== kept private copy: $COPY_DIR"; else rm -rf "$COPY_DIR"; fi
  fi
}
trap cleanup EXIT

if [ "$COPY" = 1 ]; then
  # One private copy per run. The realpath'd source strings are what
  # the fixture's files name (session.zon / session.json / the HTTP
  # history); the as-given absolute forms are rewritten too, in case a
  # file was written through a symlink.
  COPY_DIR=$(real "$(mktemp -d)")
  SRC_WS=$(real "$WS"); SRC_RS=$(real "$RS"); SRC_ZG=$(real "$ZG")
  ALT_WS=$(abs "$WS");  ALT_RS=$(abs "$RS");  ALT_ZG=$(abs "$ZG")
  cp -R "$SRC_WS" "$COPY_DIR/ws"; cp -R "$SRC_RS" "$COPY_DIR/rs-data"; cp -R "$SRC_ZG" "$COPY_DIR/zig-data"
  # Stale IPC output from an earlier run (events.jsonl / status.json /
  # screen.txt / command) is regenerated by the editors; drop it so it
  # neither carries the old path nor replays anyone's commands.
  rm -rf "$COPY_DIR/ws/.mnml/ipc" "$COPY_DIR/ws/.mnml/ipc-zig"
  WS=$COPY_DIR/ws; RS=$COPY_DIR/rs-data; ZG=$COPY_DIR/zig-data
  repoint() { # from to — every text file under the copy
    local from=$1 to=$2 f
    [ "$from" != "$to" ] || return 0
    grep -rIlF -- "$from" "$COPY_DIR" 2>/dev/null | while IFS= read -r f; do
      # `|` never occurs in a mktemp path; a source path holding one
      # would need another delimiter. Rewritten through a temp file and
      # `cat` so the file keeps its mode (the history file is 0600).
      sed "s|$from|$to|g" "$f" >"$f.ui-diff~" && cat "$f.ui-diff~" >"$f"; rm -f "$f.ui-diff~"
    done
  }
  # Longest source first, so one nested under another (RS_DATA inside
  # WS, say) is renamed before its parent's prefix is.
  printf '%s\t%s\n' "$SRC_WS" "$WS" "$ALT_WS" "$WS" "$SRC_RS" "$RS" "$ALT_RS" "$RS" "$SRC_ZG" "$ZG" "$ALT_ZG" "$ZG" \
    | awk -F'\t' '{ print length($1) "\t" $0 }' | sort -t "$(printf '\t')" -k1,1nr | cut -f2- \
    | while IFS=$(printf '\t') read -r from to; do repoint "$from" "$to"; done
  # Prove the rewrite: nothing in the copy may still name a source.
  for p in "$SRC_WS" "$ALT_WS" "$SRC_RS" "$ALT_RS" "$SRC_ZG" "$ALT_ZG"; do
    case $p in "$COPY_DIR"/*) continue ;; esac
    left=$(grep -rIlF -- "$p" "$COPY_DIR" 2>/dev/null)
    [ -z "$left" ] || { echo "ui-diff: source path $p still named in:" >&2; echo "$left" | sed 's/^/  /' >&2; exit 70; }
  done
  echo "== private copy: $COPY_DIR (KEEP=1 keeps it)"
else
  # In place: both editors persist the session (open files, cursors)
  # under `$WS/.mnml/`; a STEPS file that opens a file would otherwise
  # be restored by the next run and change its screen. Snapshot before,
  # restore after.
  SESSION_BAK=$(mktemp -d)
fi

run_one() { # name bin data ipcdir [sessions-home]
  local name=$1 bin=$2 data=$3 ipc="$WS/.mnml/$4" shome=${5:-}
  rm -rf "$ipc"
  save_session
  MNML_SESSIONS_HOME=$shome MNML_DATA_ROOT=$data MNML_COLS=$COLS MNML_ROWS=$ROWS "$bin" --headless --input standard "$WS" >"$OUT/$name.log" 2>&1 &
  local pid=$!
  for _ in $(seq 1 80); do grep -q '"start"' "$ipc/events.jsonl" 2>/dev/null && break; sleep 0.1; done
  sleep 0.8
  if [ -n "$STEPS" ]; then while IFS= read -r line; do [ -n "$line" ] && echo "$line" >>"$ipc/command"; sleep 0.4; done <"$STEPS"; sleep 0.8; fi
  cp "$ipc/screen.txt" "$OUT/$name.txt" 2>/dev/null || echo "(no screen.txt)" >"$OUT/$name.txt"
  echo '{"cmd":"quit"}' >>"$ipc/command"
  for _ in $(seq 1 30); do kill -0 $pid 2>/dev/null || break; sleep 0.1; done
  kill $pid 2>/dev/null; wait $pid 2>/dev/null
  restore_session
}
run_one rust "$RUST" "$RS" ipc
# The Zig side reads its sessions under an empty home: its start
# surface lists the workspace's Claude / Codex sessions from `~/.claude`
# / `~/.codex`, and the fixture's workspace is named like others on this
# machine — the developer's own transcripts must never reach a dump.
ZIG_SESSIONS_HOME=$(mktemp -d)
run_one zig  "$ZIG"  "$ZG" ipc-zig "$ZIG_SESSIONS_HOME"
rm -rf "$ZIG_SESSIONS_HOME"
echo "== rust: $OUT/rust.txt   zig: $OUT/zig.txt"
diff --label rust --label zig "$OUT/rust.txt" "$OUT/zig.txt" >"$OUT/screen.diff"
n=$(grep -c '^[<>]' "$OUT/screen.diff"); echo "== differing lines: $n  ($OUT/screen.diff)"
# The rail (columns 0-3) diverges from Rust's by design (AGENTS / CLOUD
# AGENTS folded into SESSIONS; a SCRIPTS row added), so a gate judges
# the rows whose columns 4+ differ. Count both.
python3 - "$OUT" <<'PY'
import sys, itertools
d = sys.argv[1]
a = open(d + '/rust.txt', encoding='utf-8', errors='replace').read().split('\n')
b = open(d + '/zig.txt', encoding='utf-8', errors='replace').read().split('\n')
rail = body = 0
for x, y in itertools.zip_longest(a, b, fillvalue=''):
    if x == y: continue
    if x[4:] == y[4:]: rail += 1
    else: body += 1
print(f"== rows differing beyond the rail: {body}  (rail-only rows: {rail})")
PY
